#!/bin/sh
#
# This file is part of ghs.
#
# ghs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ghs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ghs.  If not, see <https://www.gnu.org/licenses/>.
#
# Copyright (c) 2016-2018 dunnhumby Germany GmbH.
# All rights reserved.

set -e

cd `dirname $0`

genchangelog()
{
        echo "$1 ($2) `lsb_release -sc`; urgency=low"
        echo
	prevtag=$(git describe --always --abbrev=0 HEAD^)
        git log --date=short --format="  * %s (%h, %cd)" "$prevtag"..HEAD |
                fold --spaces --width 76 | sed 's/^\([^ ]\+\)/    \1/'
        echo
        echo " -- $3  `LANG=C date -R`"
}

pkgversion=$(git describe --dirty | cut -c2- |
		sed 's/-\([0-9]\+\)-\(g[0-9a-f]\+\)/+\1~\2/' |
		sed 's/\(~g[0-9a-f]\+\)-dirty$/-dirty\1/' |
		sed 's/-dirty/~dirty.'`date +%Y%m%d%H%M%S`'/'
	)-$(lsb_release -cs)

pkgmaint=$(echo "`git config user.name` <`git config user.email`>")

changelog=`mktemp`
trap "rm -f '$changelog'; exit 1" INT TERM QUIT

pkgname=ghs
genchangelog "$pkgname" "$pkgversion" "$pkgmaint" > "$changelog"
fpm -s dir -t deb -n "$pkgname" -v "$pkgversion" \
	--architecture all \
	--maintainer "$pkgmaint" \
	--description "A simple GitHub API scripts manager for Python" \
	--url 'https://github.com/sociomantic/ghs' \
	--vendor 'dunnhumby Germany GmbH' \
	--license GPL-3.0-or-later \
	--category devel \
	--depends python2.7 \
	--deb-changelog "$changelog" \
	--config-files /etc/ghsrc \
	ghsrc=/etc/ghsrc \
	../ghsrc.example=/usr/share/ghs/doc/ghsrc.example \
	install/usr=/

